In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.2'

In [16]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
array=np.linspace(0, 21, num=21, endpoint=False)

In [17]:
array

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20.])

In [38]:
array2=array[:22:2]

In [39]:
array2

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [40]:
array3=array[:22:3]

In [41]:
array3

array([ 0.,  3.,  6.,  9., 12., 15., 18.])